name: Build Files App (Bleeding Edge)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # تثبيت .NET 10 التجريبي للحصول على MSBuild 18
    - name: Setup .NET 10 Preview
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        include-prerelease: true

    - name: Restore Packages
      # استخدام dotnet restore للتعامل مع .slnx
      run: dotnet restore Files.slnx

    - name: Build Solution
      run: |
        # تم وضع "Sideload Only" بين علامات تنصيص لإصلاح خطأ MSB1008
        dotnet build Files.slnx -c Release -p:Platform=x64 -p:AppxPackageSigningEnabled=false -p:UapAppxPackageBuildMode="Sideload Only"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Files-Experimental-Build
        path: |
          src/Files/AppPackages/
          src/Files/bin/x64/Release/
        if-no-files-found: warn
